[TestDataGenerator] Добавить сервис для наполнения БД тестовыми данными
RAMRUSH40F/GorElectroTrans_commercial pull request #26
Opened 2024-04-28 22:50 UTC by RAMRUSH40F

2024-04-28 22:51 UTC, RAMRUSH40F commented on src/main/java/project/repository/multiplier/TestDataGenerator.java
> +@Lazy
Не загружаются в контекст, если не вызываем

2024-04-28 22:52 UTC, RAMRUSH40F commented on src/main/java/project/repository/multiplier/StudentMultiplier.java
> +    public static final List<String> RANDOM_NAME_LIST = List.of("Стремглав Вячеслав Игоревич", "Семен Иванович Дмитриевич", "Треуголова София Дмитриевна", "Рябичев Даниил Алексендрович", "Теска Кирил
если это не статик переменная, то при каждом вызове addAllStudents создается коллекция

2024-04-28 22:53 UTC, RAMRUSH40F commented on src/main/java/project/repository/multiplier/StudentMultiplier.java
> +        log.info("lessonMultiplier ended work: departmentDatabase={}", departmentId);
обратите внимание на формат логирования
"сообщение низменяемое: переменная={}", значение переменной

это давно принятый формат, на работе у меня точно так же

2024-04-28 22:53 UTC, RAMRUSH40F commented on src/main/java/project/Application.java
> +        //context.getBean(TestDataGenerator.class).addTestData();
вызов autowired поля в статик методе не возможен если что

2024-04-28 23:06 UTC, RAMRUSH40F commented on src/main/java/project/repository/multiplier/StudentMultiplier.java
> +        log.info("lessonMultiplier ended work: departmentDatabase={}", departmentId);
Вот пример логирования от работы сервиса(не все базы заполнял 
![image](https://github.com/RAMRUSH40F/GorElectroTrans_commercial/assets/91630583/688d3fa8-c566-4388-a6f7-5670bc7af687)

2024-04-29 05:57 UTC, Restout commented on src/main/java/project/repository/multiplier/TestDataGenerator.java
> +@Lazy
Крутая фича

2024-04-29 06:00 UTC, Restout commented on src/main/java/project/repository/multiplier/StudentMultiplier.java
> +    public static final List<String> RANDOM_NAME_LIST = List.of("Стремглав Вячеслав Игоревич", "Семен Иванович Дмитриевич", "Треуголова София Дмитриевна", "Рябичев Даниил Алексендрович", "Теска Кирил
Вроде не имеет смысл:
У нас бин синглтон, то есть при каждой попытке иньекции у нас будет один и тот же экземпляр класса, следовательно список создаваться заново не будет

2024-04-29 06:01 UTC, Restout commented on src/main/java/project/repository/multiplier/StudentMultiplier.java
> +        log.info("lessonMultiplier ended work: departmentDatabase={}", departmentId);
Хорошей практикой будет указывать не только окончание работы метода, но и его начало
Started
Ended

2024-04-29 06:04 UTC, Restout commented on src/main/java/project/repository/multiplier/StudentMultiplier.java
> +    public static final List<String> RANDOM_NAME_LIST = List.of("Стремглав Вячеслав Игоревич", "Семен Иванович Дмитриевич", "Треуголова София Дмитриевна", "Рябичев Даниил Алексендрович", "Теска Кирил
Но минусов для статика не вижу

2024-04-29 06:05 UTC, Restout commented on src/main/java/project/Application.java
> +        //context.getBean(TestDataGenerator.class).addTestData();
Альтернативно можно попробовать @PostConstruct метод

2024-04-29 06:13 UTC, Restout commented on src/main/java/project/repository/multiplier/TestDataGenerator.java
> +    public void addTestData(int numberOfDepartments) {
Зачем параметр? Для гибкости дополнительного заполнения ?
Если нет, то можно использовать внутри DEPARTMENTS_COUNT

2024-04-29 06:16 UTC, Restout requested changes
Добавь, пожалуйста, логирование начала выполнения методов
Спасибо

2024-04-29 08:52 UTC, RAMRUSH40F commented on src/main/java/project/repository/multiplier/StudentMultiplier.java
> +    public static final List<String> RANDOM_NAME_LIST = List.of("Стремглав Вячеслав Игоревич", "Семен Иванович Дмитриевич", "Треуголова София Дмитриевна", "Рябичев Даниил Алексендрович", "Теска Кирил
Не понятно я написал: раньше коллекция была в методе, поэтому каждый раз могла создаваться, я полагаю. Поправил

2024-04-29 08:54 UTC, RAMRUSH40F commented on src/main/java/project/Application.java
> +        //context.getBean(TestDataGenerator.class).addTestData();
Как это будет работать?

2024-04-29 08:56 UTC, RAMRUSH40F commented on src/main/java/project/repository/multiplier/TestDataGenerator.java
> +    public static final int DEPARTMENTS_COUNT = 15;
В репозитории это единственное использование, пока рано, но идея хорошая

2024-04-29 09:03 UTC, RAMRUSH40F commented on src/main/java/project/repository/multiplier/StudentMultiplier.java
> +        log.info("lessonMultiplier ended work: departmentDatabase={}", departmentId);
добавил

2024-04-29 09:04 UTC, RAMRUSH40F commented on src/main/java/project/repository/multiplier/TestDataGenerator.java
> +    public void addTestData(int numberOfDepartments) {
два метода: добавить на всех и добавить на определенные базы. Я бы только вторым пользовался, быстрее заполняется

2024-04-29 09:31 UTC, Restout commented on src/main/java/project/Application.java
> +        //context.getBean(TestDataGenerator.class).addTestData();
Следующим образом: После того, как бин Application соберется, то есть прогрузятся все бины и зависимости, вызовется PostConstruct метод, где мы вызываем заполнение 
![Снимок экрана 2024-04-29 123130](https://github.com/RAMRUSH40F/GorElectroTrans_commercial/assets/101528820/12716156-497c-4da9-ab40-6cda68aee4ff)

2024-04-29 09:33 UTC, Restout commented on src/main/java/project/Application.java
> +        //context.getBean(TestDataGenerator.class).addTestData();
Как я сейчас выяснил PostConstruct, будет вызваться еще до main метода

2024-04-29 09:43 UTC, Restout commented on src/main/java/project/repository/multiplier/SubdepartmentMultiplier.java
Нужно добавить логирование в начале выполнения метода

2024-04-29 10:06 UTC, Restout approved these changes

2024-04-29 10:08 UTC, merged