kust
RAMRUSH40F/GorElectroTrans_commercial pull request #28
Opened 2024-04-29 17:27 UTC by Gachikust

2024-04-29 17:59 UTC, RAMRUSH40F requested changes
Каждый коммент надо обдумать и 
1. ответить что не будешь вносить изменения, тогда желательно ответить почему
2. внести правки и ответить, что внес правки

2024-04-29 17:59 UTC, RAMRUSH40F commented on src/main/resources/SQL/AddComment.SQL
> +    ADD comment text NOT NULL;
1.TEXT слишком большой для коммента. Будет в среднем 2-3 предложения, а это  60-70 символов. Можем ограничиться varchar(100). Если я правильно посмотрел, text  это 65 535 слов
2.default значения какое?
3.Что будет происходить с существующими уроками, у них какой коммент в бд будет?

Я бы сделал nullable поле Lesson.comment, т.к. не у всех занятий есть комментарий. Коммент оставляют, когда меняеют статус, у статуса запланировано комментариев нет. 

На фронте будет открываться комментарий при наведение на флажок. Флажок у строки есть, если есть коммент. Различать, есть ли коммент можно на === null, а можно ==""  как планируется сейчас. Есть только один минус сейчас состояние без комментария то есть чел поменял урок и не оставил коммент и состояния отдельных.
По п.3 либо notnull и default 
либо nullable  в .sql , в Lesson @Nullable , lessonMultiplie

4. расширение файлов .sql не видел чтобы писали .SQL

2024-04-29 17:59 UTC, RAMRUSH40F commented on src/main/resources/SQL/AddComment.SQL
> +USE dep_1;
Сделать в транзакции скрипт, то есть begin transaction..., чтобы если что-то не выполнилось, все окатилось. Так безопаснее у них на сервере будет запускать. Я у себя тоже сделаю так же

2024-04-29 17:59 UTC, RAMRUSH40F commented on src/main/resources/SQL/AddStatus.SQL
> +    ADD status varchar(50) NOT NULL DEFAULT 'PLANNED' ;
varchar(50) -> varchar(20) потому что неиспользумые символы все равно заняты

2024-04-30 10:37 UTC, RAMRUSH40F commented on src/main/resources/SQL/AddComment.SQL
> +USE dep_1;
@Gachikust  почитал подробнее, транзации на уровне бд dep_1 dep_2 неработают.

Вмержил свою задачку https://github.com/RAMRUSH40F/GorElectroTrans_commercial/pull/27/files#diff-a12ca11d64ab152d7469ee952a78b9c3e338179ac933ff20153a28e896de7780R2 ,
1. сделай в те же папки.
2. укажи версию(важно при порядке накатывания скриптов, при порядке отката) в названии файла V1.3_....
3. скрипт отката в папку rollback который надо исполнить чтобы вернуться с версии v1.3 на v1.2

2024-04-30 10:52 UTC, RAMRUSH40F commented
Не хватает теста
1.Добавил записи через ручку restTemplate POST /dep_{N}/work_plan/data через создание урока. 
2 .Как-то проверить что сохранилось
3. Обновить статус и коммент через запрос  changeLesson  PUT /dep_{N}/work_plan/{id} 
4. Сделал запрос restTemplate и получил данные в формате Lesson[].class
проверил что в них есть твои новые поля и в них норм данные, те что ты добавлял в п.1 и изменил в п.2

2024-04-30 13:04 UTC, RAMRUSH40F commented
когда будешь мерджить выбери стратегию squash and merge : у тебя в мастере будет 1 коммент и укажи для него название отражающее суть вносимых изменений
![image](https://github.com/RAMRUSH40F/GorElectroTrans_commercial/assets/91630583/2a00d39f-a6da-452d-bc70-402709d180ea)

2024-04-30 13:49 UTC, RAMRUSH40F commented
1.лишний [AddComment.SQL](https://github.com/RAMRUSH40F/GorElectroTrans_commercial/pull/28/files#diff-945d4fe45b1f44ac53e9bc3de60562de07c33947fe6166af7cbd5e1f17513042)
2.теста нет. Будешь делать?
3.не ответил ни на один коммент
4. почему-то создаешь уроки с пустыми комментариями, хотя целевой сценарий после твоих правок, что у уроков null в начале, а коммент добавляется только потом

2024-05-11 10:12 UTC, Gachikust commented on src/main/resources/SQL/AddStatus.SQL
> +    ADD status varchar(50) NOT NULL DEFAULT 'PLANNED' ;
Изменил на varchar(20)

2024-05-11 10:12 UTC, Gachikust commented on src/main/resources/SQL/AddComment.SQL
> +USE dep_1;
Перенес в нужные папки, изменил названия

2024-05-11 10:13 UTC, Gachikust commented on src/main/resources/SQL/AddComment.SQL
> +    ADD comment text NOT NULL;
Комментарии сделал nullable, тип данных varchar(1000), занимает места на 1 байт больше, но позволяет избавиться от жесткого ограничения в символах. Места varchar занимает по количеству символов.

2024-05-11 20:00 UTC, RAMRUSH40F commented on src/main/resources/SQL/AddComment.SQL
> +    ADD comment text NOT NULL;
тип данных varchar(1000), занимает места на 1 байт больше, но позволяет избавиться от жесткого ограничения в символах. Места varchar занимает по количеству символов.

Можно ссылку пж не могу найти.

Символы хранятся utf8 utf16,  то есть 1 байт=1 символ или 2 байта за символ. Не может 1000 символов весить больше 100 символов на 1 байт всего лишь.

Я думаю, что 1 байт про другое имело ввиду

2024-05-11 20:11 UTC, RAMRUSH40F approved these changes
Все гуд

2024-05-11 20:11 UTC, RAMRUSH40F commented on src/test/java/project/e2eTests/LessonApiTest.java
> +        // Retrieve the saved student from the response body
```suggestion
        // Retrieve the saved lesson from the response body
```

2024-05-11 20:23 UTC, merged