Artem
RAMRUSH40F/GorElectroTrans_commercial pull request #30
Opened 2024-05-04 20:15 UTC by Restout

Docker Compose and data generation controller

2024-05-04 20:33 UTC, RAMRUSH40F requested changes
DataGenerationController

2024-05-04 20:33 UTC, RAMRUSH40F commented on src/main/resources/application-docker.properties
> +spring.jpa.database-platform=org.hibernate.dialect.MariaDB103Dialect
maria.db.url=jdbc:mariadb://database_mariadb:3306
maria.db.user=root
maria.db.password=testpass 
1.Ок оставляем, чтобы можно было быстро менять.  Но остальное зачем?
2. Можешь сверху файла оставить коммент а-ля что этот конфиг активируется когда профайл... перетирает дефолт занчения...

2024-05-04 20:33 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +        final String fileName = "src/main/resources/report_template.xls";
Большой лайк за работающие отчеты

2024-05-04 20:33 UTC, RAMRUSH40F commented on src/main/java/project/controller/DataGenerationController.java
> +    public String generateData() {
Я бы добавил в название метода Test:  generateTestData() и класс TestData... и перенес бы его в repository/multiplier. Там сейчас репы, TestDataGenerator  по сути сервис и этот контроллер будут. Мб multiplier пора вынести из repository - мб свою папку как security

Надо ли дать Кириллу возможность самому выбирать департамент?  
/dep_{N}/generateTestData()

2024-05-04 20:33 UTC, RAMRUSH40F commented on src/main/java/project/controller/DataGenerationController.java
> +        return "Data was Successfully Generated!";
Заполнение Бд работает за пару десяток секунд, нельзя так долго держать http соединение - не по канону что ли. Лучше поставить задачу на выполнение и ответь, что тестовые данные начали заполняться. И отпусти пользователя. на фронте он сразу может тогда нажимать. А так возможно придется ждать пока заполниться - смотря как кнопку реализует.  Сейчас на фронте кнопка отпускается, как придет ответ об успехе добавления

2024-05-04 20:33 UTC, RAMRUSH40F commented on src/main/java/project/controller/DataGenerationController.java
> +        log.info("Start Filling Data Base, Active Profile is Docker");
Active Profile is Docker это в другом месте вроде выводится должно.
Filling  с маленькой

2024-05-04 20:41 UTC, Restout commented on src/main/java/project/service/reportService/ReportService.java
> +        final String fileName = "src/main/resources/report_template.xls";
только локально))

2024-05-04 20:41 UTC, Restout commented on src/main/resources/application-docker.properties
> +spring.jpa.database-platform=org.hibernate.dialect.MariaDB103Dialect
если марию вдрууг менять будем или что-то
Но вообще да, можно убрать

2024-05-05 10:16 UTC, RAMRUSH40F commented on src/main/java/project/controller/DataGenerationController.java
> +        return "Data was Successfully Generated!";
как лучше постравить не знаю. Можно в Runnable запихнуть логику  и все

2024-05-05 10:28 UTC, Restout commented on src/main/java/project/controller/DataGenerationController.java
> +        return "Data was Successfully Generated!";
Два решения
1. Забить, это не повлияет, tomcat по умолчанию имеет pool потоков, можно настроить его размер в properties
Суть в том, что помимо вот этого длинного потока есть и другие, которые спокойно могут работать. У нас не такое большое количество пользователей+ методо чисто для теста, проблем быть нет
2. Перейти на webflux и использовать асинхронные запросы 

Я предлагаю первое, не приоритетное изменение

2024-05-05 10:29 UTC, Restout commented on src/main/java/project/controller/DataGenerationController.java
> +        log.info("Start Filling Data Base, Active Profile is Docker");
Исправил

2024-05-05 10:30 UTC, Restout commented on src/main/java/project/controller/DataGenerationController.java
> +    public String generateData() {
Так и сделал по итогу
Будет сам выбирать

2024-05-05 10:35 UTC, RAMRUSH40F commented on src/main/java/project/controller/DataGenerationController.java
> +        return "Data was Successfully Generated!";
@Restout 
Я говорю, что проблема не в производительности и не в том, что поток занят, а что клиент (фронтенд) ждет ответа об окончание заполнения тестовой базы, хотя это ему не нужно, ему не нужен ответ в целом, зачем ждать 10 сек+.

Я прошу отдавать ему ответ о том, что мы успешно начали заполнять и все.

2024-05-05 10:37 UTC, RAMRUSH40F approved these changes
В остальном все ок

2024-05-05 10:37 UTC, RAMRUSH40F commented on src/main/java/project/controller/DataGenerationController.java
> +    //TODO: Поправить баг, когда не меняется datasource в процессе одного метода
задачку завести в youtrack а мусор удалить

2024-05-05 11:02 UTC, merged