Fix path issue in reports
RAMRUSH40F/GorElectroTrans_commercial pull request #32
Opened 2024-06-09 13:08 UTC by Restout

2024-06-09 15:02 UTC, RAMRUSH40F requested changes
Внес некоторые правки сам, некоторые правки запросил. Не до конца понятна логика сейчас. Когда будешь переписывать на новую версию xlxs, обратить внимание на читаемость после. Вряд ли хе-хе будем ещё править, после себя надо либо чисто оставить, либо много комметов // копируем, иначе ... // это чтобы ...

Много своих комментов сам поправил уже в коде и пушнул

2024-06-09 16:03 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +            this.tempFile = File.createTempFile("temp_report", "xls");
это чтобы после 1млн копий файл не сломался?

2024-06-09 16:03 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +    private void creatTeacherReportPart(HSSFSheet sheet, Map.Entry<Integer, Integer> yearMonthPair) {
!!!
Мб в LocalDate хранить месяц и год? День ставишь первый.

Код станет прозрачней. Переменная будет LocalDate beforeDate или как-то и нормально будет использовать в ReportRepository. Сейчас Map.Entry<Integer, Integer> yearMonthPair мракобесие

2024-06-09 16:30 UTC, Restout commented on src/main/java/project/service/reportService/ReportService.java
> +    private void creatTeacherReportPart(HSSFSheet sheet, Map.Entry<Integer, Integer> yearMonthPair) {
Я ещё даже не трогал это, куда смотрим 😕

2024-06-09 16:40 UTC, Restout commented on test-runner.exec
Да, непонятно как залетел

2024-06-12 11:50 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +    private void creatTeacherReportPart(HSSFSheet sheet, Map.Entry<Integer, Integer> yearMonthPair) {
@Restout  это поправишь или потом или не будешь?

2024-06-12 17:02 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +        try (InputStream inputStream = Objects.requireNonNull(getClass().getResourceAsStream(REPORT_TEMPLATE_PATH))) {
заесбись

2024-06-12 17:03 UTC, RAMRUSH40F approved these changes

2024-06-12 17:06 UTC, merged