[AttendanceReport] Добавлена выгрузка из журнала посещаемости
RAMRUSH40F/GorElectroTrans_commercial pull request #34
Opened 2024-06-17 19:32 UTC by Gachikust

Данные из журнала посещаемости за определенное время
Пример запроса: http://localhost:8082/dep_1/report/attendance?dateFrom=1970-01-15&dateTo=1970-01-22
Обе даты включительно

2024-06-17 20:35 UTC, RAMRUSH40F commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +    public XSSFWorkbook AttendanceReport(Integer departmentId, LocalDate dateFrom, LocalDate dateTo){
camelCase

2024-06-17 20:37 UTC, RAMRUSH40F commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +            OPCPackage pkg = OPCPackage.open(inputStream);
лишнее

2024-06-17 20:47 UTC, RAMRUSH40F commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +        attendanceDataMas[0]=attendance.getLessonId().toString();
🤢

2024-06-17 20:50 UTC, RAMRUSH40F commented on src/main/java/project/repository/AttendanceReportJpaRepository.java
> +    @Query("select a from Attendance a "+
1.Какой запрос идет в базу
2.Проверить что по индексу

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

2024-06-17 20:58 UTC, RAMRUSH40F requested changes
Дал комменты тут и голосом в дискорде.

2024-06-18 15:09 UTC, Restout commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +    public XSSFWorkbook AttendanceReport(Integer departmentId, LocalDate dateFrom, LocalDate dateTo){
Это шарпы так плохо влияют

2024-06-18 15:19 UTC, Restout commented on src/main/java/project/controller/AttendanceController.java
> +        }
Не знаю, говорил Рамиль или нет, запись в outputStream можно не делать совсем. 
Это нужно для сохранения в физический файл. Тут же можем просто отдать ByteArray полученный из XSSFWorkbook

2024-06-18 15:26 UTC, Restout commented on src/main/java/project/repository/AttendanceJpaRepository.java
> +            "where a.lesson.date >=:dateFrom AND a.lesson.date<=:dateTo")
Можно ли сделать beetwen? Будет более читаемо

2024-06-18 15:30 UTC, Gachikust commented on src/main/java/project/controller/AttendanceController.java
> +        }
Если ты про метод getBytes() то его нет у XSSFWorkbook

2024-06-18 15:31 UTC, Restout commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +        String[] attendanceDataMas;
Массив нигде не используется.
Вместо переменной k и foreach сделай простой for

2024-06-18 15:32 UTC, Gachikust commented on src/main/java/project/repository/AttendanceJpaRepository.java
> +            "where a.lesson.date >=:dateFrom AND a.lesson.date<=:dateTo")
Можно, но и так работает

2024-06-18 15:33 UTC, Restout commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +    private void setDataToRow(XSSFRow row,CellStyle style,Attendance attendance){
style можно вынести в поле класса

2024-06-18 15:33 UTC, Restout commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +        for (int i=0;i<8;i++) {
magicNumber

2024-06-18 15:35 UTC, Restout commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +        for (int i=0;i<8;i++) {
Можно ли этот for красиво вынести в отдельный метод ?

2024-06-18 15:39 UTC, Restout commented on src/main/java/project/repository/AttendanceJpaRepository.java
> +            "where a.lesson.date >=:dateFrom AND a.lesson.date<=:dateTo")
Понимаю, но beetwen как раз для таких случаев и нужен + сразу понятен, не нужно смотреть, строгое, не строгое неравенство, понимать, что к чему

2024-06-18 15:43 UTC, Restout commented on src/main/java/project/controller/AttendanceController.java
> +        }
Пон, на докере тестирование проводилось ?

2024-06-18 16:19 UTC, RAMRUSH40F commented on src/main/java/project/controller/AttendanceController.java
> +        }
> в outputStream можно не делать совсем 
Он не записывает в физический файл, а просто создаем обертку над byte[]

В Докере что-то может не работать, например, пути к файлам - так была с отчетами Артема, мб тут тоже. Сейчас у Артема все работает и в докере и без.

Но не критично, ибо докер в этой задачке вне нашей практики

2024-06-18 16:20 UTC, RAMRUSH40F commented on src/main/java/project/repository/AttendanceJpaRepository.java
> +            "where a.lesson.date >=:dateFrom AND a.lesson.date<=:dateTo")
@Gachikust  Артем говорит использовать between 
where a.lesson.date between :dateFrom AND a.lesson.date :dateTo

Мб mysql их оптимизировано как-то выполняет, понимания у меня нет

2024-06-18 16:21 UTC, RAMRUSH40F commented on src/main/java/project/repository/LessonJpaRepository.java
> +    @Query("SELECT COUNT(l) FROM Lesson l WHERE l.date>=:dateFrom and l.date<:dateTo and l.status='HELD' ")
@Restout  смотрим новое поле

2024-06-18 16:23 UTC, RAMRUSH40F commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +        log.info("Начало создания выгрузки");
выгрузки из журнала посещаемости
Параметры запроса залогируются сами

2024-06-18 16:31 UTC, RAMRUSH40F commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +public class AttendanceReportServiceImpl {
Это обязан лежать в service/reportService в таком вариант либо переименовать папку reportService
А еще лучше AttendanceReportServiceImpl  -> AttendanceExcelExporter, AttendanceExcelCreator, AttendanceExportService.

Я подумал и лучшее AttendanceExcelExporter

2024-06-18 17:11 UTC, Gachikust commented on src/main/java/project/repository/AttendanceJpaRepository.java
> +            "where a.lesson.date >=:dateFrom AND a.lesson.date<=:dateTo")
Сделал beetwen

2024-06-18 17:11 UTC, Gachikust commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +        String[] attendanceDataMas;
Поправил

2024-06-18 17:11 UTC, Gachikust commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +    private void setDataToRow(XSSFRow row,CellStyle style,Attendance attendance){
Вынес с ноги

2024-06-18 17:12 UTC, Gachikust commented on src/main/java/project/service/AttendanceReportServiceImpl.java
> +        for (int i=0;i<8;i++) {
for вынес

2024-06-18 17:20 UTC, merged

2024-06-18 18:09 UTC, Restout commented on src/main/java/project/controller/AttendanceController.java
> +        }
Докер - то как у них лежать все будет
Условно тест на рабочей среде с докером

2024-06-18 18:10 UTC, Restout commented on src/main/java/project/repository/LessonJpaRepository.java
> +    @Query("SELECT COUNT(l) FROM Lesson l WHERE l.date>=:dateFrom and l.date<:dateTo and l.status='HELD' ")
Видел да, хорошее