[StudentImport] Загрузка студентов из Excel файла
RAMRUSH40F/GorElectroTrans_commercial pull request #35
Opened 2024-06-20 13:29 UTC by Gachikust

Добавление студентов через excel файл

GET http://localhost:8082/dep_1/students/studentAddTemplate - скачать шаблон для загрузки студентов

POST http://localhost:8082/dep_1/students/importStudent - загрузка файла

2024-06-20 15:01 UTC, RAMRUSH40F requested changes
Ответь на комменты или поправь. Обсуждение приветствуется.
Критично поправить ImportedStudents

2024-06-21 00:56 UTC, Gachikust commented on src/main/java/project/exceptions/Validator.java
> +        if (id.length() != 5 || !id.matches("[0-9]+")) {
Использовал

2024-06-21 00:56 UTC, Gachikust commented on src/main/java/project/service/StudentImportServiceImpl.java
> +    public XSSFWorkbook getStudentAddTemplate(){
Метод переименовал
строка не нужна

2024-06-21 00:57 UTC, Gachikust commented on src/main/java/project/controller/StudentController.java
> +            students = studentAddService.importStudent(workbook,departmentId);
Переименовал

2024-06-21 00:57 UTC, Gachikust commented on src/main/java/project/controller/StudentController.java
> +        headers.setContentDispositionFormData("attachment", "Шаблон_загрузки_студентов.xlsx");
Название выгрузки изменил

2024-06-21 01:09 UTC, Gachikust commented on src/main/java/project/model/ImportedStudents.java
> +    private List<Student> createdStudents = new ArrayList<Student>();
Вроде сделал.
Вопрос почему плохой паттерн? По идее доступа к коллекциям внутренним не должно быть, это можно сделать возвращая копию коллекции из геттеров.
Еще один вопрос нужно ли в данном случае переопределять геттеры, поскольку стандартный возвращает ссылку, по которой можно изменить коллекцию?

2024-06-21 01:14 UTC, Gachikust commented on src/main/java/project/service/StudentImportServiceImpl.java
> +                Optional<Subdepartment> optionalSubdepartment = subdepartmentJpaRepository.findById(subdepartamentId);
Использовал

2024-06-21 01:17 UTC, Gachikust commented on src/main/java/project/service/StudentImportServiceImpl.java
> +                    Student student = new Student(studentId,subdepartment.getId(),studentName,subdepartment);
Использовал builder. subdepartment все таки нужен, без него нельзя получить subdepartmentName при отдаче

2024-06-21 08:35 UTC, RAMRUSH40F commented on src/main/java/project/model/ImportedStudents.java
> +    private List<Student> createdStudents = new ArrayList<Student>();
По идее доступа к коллекциям внутренним не должно быть. Нет при передаче в конструктор у тебя ссылка остается в коде и можешь что-то добавлять.  В get можешь отдавать новое тоже, или использовать в полях неизменяемый List. Второй вариант тоже правильнее

2024-06-21 08:40 UTC, RAMRUSH40F commented on src/main/java/project/service/StudentImportServiceImpl.java
> +                Optional<Subdepartment> optionalSubdepartment = subdepartmentJpaRepository.findById(subdepartamentId);
К этому комменту и комменту ниже:
Сори что напугал, но если Subdepartment надо доставать все равно чтобы добавить в Student объект, тогда упрощение логики с existBy несет скорее вред, потому что у тебя 2 запроса теперь (. 
Я думаю, если нет возможность отправлять только existBy, то нужен один запрос на достать subdepartment как было раньше

2024-06-21 08:41 UTC, RAMRUSH40F commented on src/main/java/project/service/StudentImportServiceImpl.java
> +            String studentId = formatter.formatCellValue(row.getCell(0));
👍

2024-06-21 08:49 UTC, RAMRUSH40F approved these changes
ImportStudent immutable и тримить данные из excel осталось

2024-06-21 08:49 UTC, RAMRUSH40F commented on src/main/java/project/service/StudentImportServiceImpl.java
> +            String studentId = formatter.formatCellValue(row.getCell(0));
перед тем как обрабатывать надо чтобы тримились поля, то есть убирались whitespaces до и после
"51445    "  сейчас не уверен, что спарсится. Это важно и может сильно портить пользовательский опыт

2024-06-21 10:03 UTC, Gachikust commented on src/main/java/project/service/StudentImportServiceImpl.java
> +                Optional<Subdepartment> optionalSubdepartment = subdepartmentJpaRepository.findById(subdepartamentId);
Вернув как было

2024-06-21 10:05 UTC, Gachikust commented on src/main/java/project/service/StudentImportServiceImpl.java
> +            String studentId = formatter.formatCellValue(row.getCell(0));
Все поля тримятся

2024-06-21 10:06 UTC, merged