Fix reports
RAMRUSH40F/GorElectroTrans_commercial pull request #38
Opened 2024-06-29 18:43 UTC by Restout

1. Теперь отчету формируются по двум датам, вместо квартальной системы
2. Исправил заполнение шаблона. Темы заполняются корректно
3. Переход на xlsx
4. Добавил индекс в базу данных
5. Правки по предыдущему коду

2024-06-29 19:12 UTC, RAMRUSH40F requested changes
а

2024-06-29 19:12 UTC, RAMRUSH40F commented on src/main/java/project/controller/ReportController.java
> +    @Deprecated
Я думал пометить deprecated старую ручку. Но если удалил ту логику, то эта не нужна тоже же, не так ли?

2024-06-29 19:12 UTC, RAMRUSH40F commented on src/main/java/project/controller/ReportController.java
> +        //validateInterval(dateFrom);
Расскомментить мб?

2024-06-29 19:12 UTC, RAMRUSH40F commented on src/main/java/project/controller/ReportController.java
> +        ByteArrayOutputStream byteArrayOutputStream = reportService.createReport(dateFrom, dateTo);
reportService.createReport должен возвращать тип отчета а не набор байтов, это разделение ответственности слоев.  А вот способ его отдать - это к контроллеру, тут toBytes() сделать или что-то по выбору слоя контроллеров

2024-06-29 19:12 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +        xssfWorkBook.getCreationHelper().createFormulaEvaluator().evaluateAll();
Вот это зачем?

2024-06-29 19:12 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +    public ByteArrayOutputStream createReport(LocalDate dateFrom, LocalDate dateTo) {
@NotNull LocalDate dateFrom, @NotNull  LocalDate dateTo

2024-06-29 19:12 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +        cellStyle = applyClassicStyle(xssfWorkBook);
не понятна судьба поля cellstyle? его можно посчитать один раз? Сейчас ты его каждый вызов считаешь

2024-06-29 19:18 UTC, Restout commented on src/main/java/project/service/reportService/ReportTemplateRowNames.java
> +    LESSON_PLAN(2),
так у нас везде count, смысла особо от этого нет имхо

2024-06-29 19:19 UTC, Restout commented on src/main/java/project/controller/ReportController.java
> +    @Deprecated
Чтобы с фронтом пока проблем не было

2024-06-29 19:22 UTC, Restout commented on src/main/java/project/controller/ReportController.java
> +        ByteArrayOutputStream byteArrayOutputStream = reportService.createReport(dateFrom, dateTo);
Сомнительно
ToByte во первых нет
Во вторых, в чем разделение отвественности?
Более сомнительно выглядит, если я в контроллере буду создавать byteArray - это уже то, как я обрабатываю данные исходя из нужд сервиса

2024-06-29 19:22 UTC, Restout commented on src/main/java/project/service/reportService/ReportService.java
> +        xssfWorkBook.getCreationHelper().createFormulaEvaluator().evaluateAll();
Формулы применяет

2024-06-29 19:22 UTC, Restout commented on src/main/java/project/service/reportService/ReportService.java
> +        xssfWorkBook.getCreationHelper().createFormulaEvaluator().evaluateAll();
Название говорящее

2024-06-29 19:24 UTC, Restout commented on src/main/java/project/service/reportService/ReportTemplateRowNames.java
> +    THEME_PLAN(4),
То есть topic_plan не будет понятно исходя из логики и шаблона?)) Окружение супер дополняет название

2024-06-29 19:27 UTC, Restout commented on src/main/java/project/service/reportService/ReportService.java
> +        cellStyle = applyClassicStyle(xssfWorkBook);
Если оставил, то нельзя
Попробую еще раз поискать возможность

2024-06-29 19:28 UTC, Restout commented on src/main/java/project/service/reportService/WorkerProfessions.java
> +    VODITELY_TR("Водители троллейбусов"),
символы дорогие нынче

2024-06-29 19:29 UTC, Restout commented on src/main/java/project/service/reportService/WorkerProfessions.java
> +    VODITELY_TR("Водители троллейбусов"),
дефицит

2024-06-29 19:31 UTC, Gachikust commented on src/main/java/project/controller/ReportController.java
> +        //validateInterval(dateFrom);
Тут validateDate используй

2024-06-29 20:41 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportTemplateRowNames.java
> +public enum ReportTemplateRowNames {
Я говорю про несоответствие имени enum и его сути, его функциональности.
Просто ReportRow - строка. например Lesson_planed. 2 - это поле строки(характеристика), обозначающее ее номер в xlxs.
Мы в enum некоторой характеристике 1,2,3,4 даем удобное обозначение, с которой можно работать. Мб тогда назвать номера строк ReportRowNumber но это звучит странно, поэтому ReportRow.

Сейчас Names ни к чему не относится из реального отчета. Имена строк отчета "Количество запланированных занятий в рабочем плане". Если бы ты это хранил, то был бы Name. А ты хранишь номера строк, поэтому ReportRowNumber, но я больше склоняюсь к ReportRow. Ничто не мешает расширить его другими полями потом

2024-06-29 20:44 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportTemplateRowNames.java
> +    LESSON_PLAN(2),
согласен.
Но появилась еще просьба поменять так:
LESSON_PLAN - урок плана
LESSON_PLANNED  запланированных уроков ( количество)
 
LESSON_**HELD** проведенных ( у нас в других частях приложения такой нейминг)

TOPIC_PLANNED
etc

2024-06-29 20:44 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportTemplateRowNames.java
> +    THEME_PLAN(4),
> не будет понятно исходя из логики и шаблона
не пон

2024-06-29 20:45 UTC, RAMRUSH40F commented on src/main/java/project/controller/ReportController.java
> +    @Deprecated
окей

2024-06-29 20:51 UTC, RAMRUSH40F commented on src/main/java/project/controller/ReportController.java
> +        ByteArrayOutputStream byteArrayOutputStream = reportService.createReport(dateFrom, dateTo);
из нужд сервиса ? из нужд контроллера ты имел в виду?

Как я обозначил 
reportService.createReport должен возвращать тип отчета. Контроллер занимается тем, чтобы отдать это в удобном виде клиенту. Сервис сейчас у тебя специально преобразует все в byteArray, потому что это требуется контроллеру, это означает нарушение разделения ответственности слоев, а именно 1.просачивание в слой сервиса знаний о том, что нужно контроллеру 2.завязывание метода сервиса под одного клиента - контроллер. Про пункт два подробнее: допустим, этот метод вызывает новый модуль по какой-то причине и получает тип ByteArray. Чтобы с ним работать, ему нужно знать, что этот набор бит это .xlxs отчет и для работы с ним нужно его преобразовывать в какой-то тип.  Причем определенного типа, только в котором можно воспринимать эти данные.

2024-06-29 20:52 UTC, RAMRUSH40F commented on src/main/java/project/service/reportService/ReportService.java
> +        cellStyle = applyClassicStyle(xssfWorkBook);
> Если оставил, то нельзя 
Звучит токсично. 

Может я не прав и ты  старый  отчет файл не удалил и не расскоментил валидацию тоже потому что нельзя было.

А по этому комменту ок

2024-06-30 06:35 UTC, Restout commented on src/main/java/project/service/reportService/ReportService.java
> +        cellStyle = applyClassicStyle(xssfWorkBook);
ноу токсисити

2024-06-30 06:52 UTC, Restout commented on src/main/java/project/service/reportService/ReportService.java
> +        cellStyle = applyClassicStyle(xssfWorkBook);
>  его можно посчитать один раз? 

какой вопрос, такой ответ
ноу токсисити

2024-06-30 07:02 UTC, Restout commented on src/main/java/project/controller/ReportController.java
> +        ByteArrayOutputStream byteArrayOutputStream = reportService.createReport(dateFrom, dateTo);
1. Можно наоборот сказать. Контроллер возвращает то, что отдает сервис. Битовый массив - стандартное представление любого набора битов в т.ч файла. Какой-то особой конвертации под формат возвращаемого значения нет. 
2.Как раз-таки наоборот, ByteArray более общий тип и более вероятно, что будет идти работа с ByteArray, чем с Workbook. 

Имхо в контроллер переводить супер сомнительно.
1. Приводим не к узкому типу, а к супер широкому
2.Применяется конкретная реализация XLSX библиотеки, если мы используем во всем интерфейсы, как основу взаимодействия, то откуда контроллер должен знать, что мы возвращаем сугубо XLSX, а не XLS например и сугубо библиотеки appache?

2024-06-30 07:04 UTC, Restout commented on src/main/java/project/controller/ReportController.java
> +        ByteArrayOutputStream byteArrayOutputStream = reportService.createReport(dateFrom, dateTo);
Прошу либо пример, либо какую-то статью на эту тему
Можно обсудить в дс

2024-06-30 09:21 UTC, Restout commented on src/main/java/project/controller/ReportController.java
> +        ByteArrayOutputStream byteArrayOutputStream = reportService.createReport(dateFrom, dateTo);
Обсудили

2024-06-30 09:27 UTC, RAMRUSH40F approved these changes

2024-06-30 10:23 UTC, Restout commented on src/main/java/project/service/reportService/ReportService.java
> +        cellStyle = applyClassicStyle(xssfWorkBook);
Так сделать вообще нельзя
You can't do that, CellStyle objects are specific to one workbook. They're quite deep objects, and much of the style is held in the workbook, so you can't just re-use

2024-06-30 11:51 UTC, merged